### ISSUE TITLE
RAD_FirstStage_include.ini needs updating (NETRAD_1_1_1 specifically) to be inline with Calculation_Procedures

### ISSUE THREAD

**Issue by rosiehoward** [CANFLUX/TAB_include_files#1]
NETRAD should be recalculated from filtered SW_IN and SW_OUT, just like ALB is. This was fixed in Calculation_Procedures, but hasn't been edited in this repo yet.

**Comment by znesic** [comment]
Updated RAD_FirstStage_include.ini to match the one in Calculation_procedures. It now uses recalculated NETRAD.

**Comment by rosiehoward** [comment]
Thank you!
